### ISSUE TITLE
结束录制后崩溃了  mediaRecorder.stop();

### ISSUE THREAD

**Issue by Daydayupe** [SMask/ScreenCaptureLibrary_Android#5]
java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at com.mask.mediaprojection.service.MediaProjectionService.stopRecording(MediaProjectionService.java:382)
        at com.mask.mediaprojection.utils.MediaProjectionHelper.stopMediaRecorder(MediaProjectionHelper.java:166)
        at com.mask.mediaprojectionlibrary.MainActivity.doMediaRecorderStop(MainActivity.java:194)
        at com.mask.mediaprojectionlibrary.MainActivity.access$400(MainActivity.java:25)
        at com.mask.mediaprojectionlibrary.MainActivity$5.onClick(MainActivity.java:100)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by SMask** [comment]
具体是怎么操作导致崩溃的呢？

**Comment by zhugefubin** [comment]
这个方法录不上声音?
